// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABDqiv2ox2QV2G-bsAlLe2O4kRW3k08GY',
    appId: '1:438949279025:web:6ed95f1553a80d5becac10',
    messagingSenderId: '438949279025',
    projectId: 'bento-buddy',
    authDomain: 'bento-buddy.firebaseapp.com',
    storageBucket: 'bento-buddy.firebasestorage.app',
    measurementId: 'G-CXF92DVSR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKa2rWVs-WGU-yI4jTonUiOwKkLBDC788',
    appId: '1:438949279025:android:3eda174eb0e8a78eecac10',
    messagingSenderId: '438949279025',
    projectId: 'bento-buddy',
    storageBucket: 'bento-buddy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMtBSfEz2_a1DtXMUKG8BPJlQDcFQb204',
    appId: '1:438949279025:ios:27287aa6645ab5cfecac10',
    messagingSenderId: '438949279025',
    projectId: 'bento-buddy',
    storageBucket: 'bento-buddy.firebasestorage.app',
    iosBundleId: 'com.example.bentoBuddy',
  );
}
